### ISSUE TITLE
VAT percentage on an Item is defined as Int, some countries (including Finland) are using decimal VAT values

### ISSUE THREAD

**Issue by lassirom** [paytrail/paytrail-ios-sdk#2]
In PaymentRequestBody.swift the Item.vatPercentage is defined as Int, Finnish standard VAT is now 25,5%

public struct Item: Codable, Equatable {
    
    /// Price per unit, in each country's minor unit, e.g. for Euros use cents. By default price should include VAT, unless usePricesWithoutVat is set to true. No negative values accepted. Maximum value of 2147483647, minimum value is 0.
    public let unitPrice: Int
    
    /// Quantity, how many items ordered. Negative values are not supported.
    public let units: Int
    
    /// VAT percentage
    public let vatPercentage: Int
...

**Comment by kotivuori** [comment]
Thanks for reporting @lassirom. We will update this shortly.

**Comment by lassirom** [comment]
@kotivuori Thanks! Works nicely now.
